version: '1.2'

name:
  cpp: Config
  sql: config

keys:
  foreign:
    - { name: frame_id, table: frames }

fields:
  dataset_id:                  { type: { name: char }, length: 2,                     desc: '' }
  tx_enable:                   { type: { name: int, bits:  8, signed: false },        desc: '' }
  tx_interval:                 { type: { name: int, bits:  8, signed: false },        desc: '' }
  tx_interval_downlink:        { type: { name: int, bits:  8, signed: false },        desc: '' }
  tx_datarate:                 { type: { name: int, bits:  8, signed: false },        desc: '' } # 4 bit 'enum' (what are the values?)
  tx_power:                    { type: { name: int, bits:  8, signed: false },        desc: '' }
  tx_overtemp:                 { type: { name: int, bits:  8, signed:  true },        desc: '' }
  rx_overtemp:                 { type: { name: int, bits:  8, signed:  true },        desc: '' }
  batt_overtemp:               { type: { name: int, bits:  8, signed:  true },        desc: '' }
  obc_overtemp:                { type: { name: int, bits:  8, signed:  true },        desc: '' }
  pa_overtemp:                 { type: { name: int, bits:  8, signed:  true },        desc: '' }
  low_voltage_threshold:       { type: { name: int, bits:  8, signed:  true },        desc: '' }
  low_voltage_recovery:        { type: { name: int, bits:  8, signed:  true },        desc: '' }
  health_acquisition_interval: { type: { name: int, bits: 16, signed: false },        desc: '' }
  configuration_acquisition_interval: { type: { name: int, bits: 16, signed: false }, desc: '' }
  imu_acquisition_interval:    { type: { name: int, bits: 16, signed: false },        desc: '' }
  imu_sample_count:            { type: { name: int, bits:  8, signed: false },        desc: '' }
  imu_sample_interval:         { type: { name: int, bits:  8, signed: false },        desc: '' }
  gps_acquisition_interval:    { type: { name: int, bits: 16, signed: false },        desc: '' }
  gps_sample_count:            { type: { name: int, bits:  8, signed: false },        desc: '' }
  gps_sample_interval:         { type: { name: int, bits:  8, signed: false },        desc: '' }
  image_acquisition_time:      { type: { name: time, bits: 32 },                      desc: '' }
  image_acquisition_profile:   { type: { name: int, bits:  8, signed: false },        desc: '' }
  time:                        { type: { name: time },                                desc: '' }
  operational_mode:            { type: { name: int, bits:  8, signed: false },        desc: '' }
  self_test:                   { type: { name: bool },                                desc: '' }
  power_rail_1:                { type: { name: bool },                                desc: '' }
  power_rail_2:                { type: { name: bool },                                desc: '' }
  power_rail_3:                { type: { name: bool },                                desc: '' }
  power_rail_4:                { type: { name: bool },                                desc: '' }
  power_rail_5:                { type: { name: bool },                                desc: '' }
  power_rail_6:                { type: { name: bool },                                desc: '' }
  reset_power_rail_1:          { type: { name: bool },                                desc: '' }
  reset_power_rail_2:          { type: { name: bool },                                desc: '' }
  reset_power_rail_3:          { type: { name: bool },                                desc: '' }
  reset_power_rail_4:          { type: { name: bool },                                desc: '' }
  reset_power_rail_5:          { type: { name: bool },                                desc: '' }
  reset_power_rail_6:          { type: { name: bool },                                desc: '' }
